name: zadatko
description: Zadatko is a simple task management application made in Flutter & Firebase.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  flutter_svg: ^0.19.0
  flutter_spinkit: ^4.1.2+1
  firebase_core: ^0.5.0
  firebase_auth: ^0.18.0+1
  cloud_firestore: ^0.14.0+2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/illustrations/
    - assets/icons/

  fonts:
    - family: Avenir
      fonts:
        - asset: assets/fonts/Avenir/AvenirNextRoundedProRegular.ttf
        - asset: assets/fonts/Avenir/AvenirNextRoundedProMedium.ttf
          weight: 500
        - asset: assets/fonts/Avenir/AvenirNextRoundedProBold.ttf
          weight: 700
    - family: Playfair Display
      fonts:
        - asset: assets/fonts/Playfair Display/PlayfairDisplay-Regular.ttf
        - asset: assets/fonts/Playfair Display/PlayfairDisplay-SemiBold.ttf
          weight: 600

