name: zadatko
description: Zadatko is a simple task management application made in Flutter & Firebase.

publish_to: 'none'

version: 1.0.1+2

environment:
  sdk: '>=2.12.0-29.10.beta <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_svg: 2.0.2
  flutter_spinkit: 5.1.0
  firebase_core: 1.0.0
  firebase_auth: 1.0.0
  cloud_firestore: 1.0.0

dev_dependencies:
  flutter_launcher_icons: 0.12.0

dependency_overrides:
  firebase_core_platform_interface: 4.5.1

flutter_icons:
  android: true
  ios: true
  image_path: 'assets/icon.png'
  adaptive_icon_background: '#212430'
  adaptive_icon_foreground: 'assets/icon.png'

flutter:
  uses-material-design: true

  assets:
    - assets/illustrations/
    - assets/icons/

  fonts:
    - family: Avenir
      fonts:
        - asset: assets/fonts/Avenir/AvenirNextRoundedProRegular.ttf
        - asset: assets/fonts/Avenir/AvenirNextRoundedProMedium.ttf
          weight: 500
        - asset: assets/fonts/Avenir/AvenirNextRoundedProBold.ttf
          weight: 700
    - family: Playfair Display
      fonts:
        - asset: assets/fonts/Playfair Display/PlayfairDisplay-Regular.ttf
        - asset: assets/fonts/Playfair Display/PlayfairDisplay-SemiBold.ttf
          weight: 600
